#!/usr/bin/make -f

all:
	make -C dompi_manager
	make -C abmev.cgi
	make -C abmassign.cgi
	make -C abmhw.cgi
	make -C abmuser.cgi

clean:
	make -C dompi_manager clean
	make -C abmev.cgi clean
	make -C abmassign.cgi clean
	make -C abmhw.cgi clean
	make -C abmuser.cgi clean

install:
	make -C dompi_manager install
	make -C abmev.cgi install
	make -C abmassign.cgi install
	make -C abmhw.cgi install
	make -C abmuser.cgi install

uninstall:
	make -C dompi_manager uninstall
	make -C abmev.cgi uninstall
	make -C abmassign.cgi uninstall
	make -C abmhw.cgi uninstall
	make -C abmuser.cgi uninstall
