#!/usr/bin/make -f

all:
	make -C abmassign.cgi
	make -C abmalarma.cgi
	make -C abmat.cgi
	make -C abmauto.cgi
	make -C abmev.cgi
	make -C abmgroup.cgi
	make -C abmhw.cgi
	make -C abmsys.cgi
	make -C abmuser.cgi
	make -C abmcamara.cgi
	make -C ctrlalarma.cgi
	make -C domcli
	make -C infoio.cgi
	make -C statusio.cgi
	make -C gmonitor_get_saf.cgi
	make -C dompi_mobile.cgi
# Pi IO
	make -C wifi.cgi
	make -C iostatus.cgi
	make -C ioswitch.cgi
	make -C ioconfig.cgi

clean:
	make -C abmassign.cgi clean
	make -C abmalarma.cgi clean
	make -C abmat.cgi clean
	make -C abmauto.cgi clean
	make -C abmev.cgi clean
	make -C abmgroup.cgi clean
	make -C abmhw.cgi clean
	make -C abmsys.cgi clean
	make -C abmuser.cgi clean
	make -C abmcamara.cgi clean
	make -C ctrlalarma.cgi clean
	make -C domcli clean
	make -C infoio.cgi clean
	make -C statusio.cgi clean
	make -C gmonitor_get_saf.cgi clean
	make -C dompi_mobile.cgi clean
# Pi IO
	make -C wifi.cgi clean
	make -C iostatus.cgi clean
	make -C ioswitch.cgi clean
	make -C ioconfig.cgi clean

install:
	make -C abmassign.cgi install
	make -C abmalarma.cgi install
	make -C abmat.cgi install
	make -C abmauto.cgi install
	make -C abmev.cgi install
	make -C abmgroup.cgi install
	make -C abmhw.cgi install
	make -C abmsys.cgi install
	make -C abmuser.cgi install
	make -C abmcamara.cgi install
	make -C ctrlalarma.cgi install
	make -C domcli install
	make -C infoio.cgi install
	make -C statusio.cgi install
	make -C gmonitor_get_saf.cgi install
	make -C dompi_mobile.cgi install
# Pi IO
	make -C wifi.cgi install
	make -C iostatus.cgi install
	make -C ioswitch.cgi install
	make -C ioconfig.cgi install

uninstall:
	make -C abmassign.cgi uninstall
	make -C abmalarma.cgi uninstall
	make -C abmat.cgi uninstall
	make -C abmauto.cgi uninstall
	make -C abmev.cgi uninstall
	make -C abmgroup.cgi uninstall
	make -C abmhw.cgi uninstall
	make -C abmsys.cgi uninstall
	make -C abmuser.cgi uninstall
	make -C abmcamara.cgi uninstall
	make -C ctrlalarma.cgi uninstall
	make -C domcli uninstall
	make -C infoio.cgi uninstall
	make -C statusio.cgi uninstall
	make -C gmonitor_get_saf.cgi uninstall
	make -C dompi_mobile.cgi uninstall
# Pi IO
	make -C wifi.cgi uninstall
	make -C iostatus.cgi uninstall
	make -C ioswitch.cgi uninstall
	make -C ioconfig.cgi uninstall
