#!/usr/bin/make -f
DOCUMENT_ROOT=/var/www/html/
CGI_ROOT=/usr/lib/cgi-bin/

CP=cp -uva


#.cc.o:
#	$(CC) $(CFLAGS) $(CXXFLAGS) $(INCLUDE) $(DEFINE) -c $<

all: none

none:
	echo "implementado solamente make install"

install:
	$(CP) * $(DOCUMENT_ROOT)

