INSERT INTO TB_DOM_PERIF (Id, MAC, Dispositivo) VALUES (0, '0000000000000000', 'Ninguno');
INSERT INTO TB_DOM_ICONO (Id, FileNamePrefix, FileNameExt) VALUES (0, 'blank', 'png');
INSERT INTO TB_DOM_ICONO (Id, FileNamePrefix, FileNameExt) VALUES (1, 'lamp', 'png');
INSERT INTO TB_DOM_ICONO (Id, FileNamePrefix, FileNameExt) VALUES (2, 'switch', 'png');
INSERT INTO TB_DOM_ICONO (Id, FileNamePrefix, FileNameExt) VALUES (3, 'window', 'png');
INSERT INTO TB_DOM_ICONO (Id, FileNamePrefix, FileNameExt) VALUES (4, 'door', 'png');
INSERT INTO TB_DOM_ICONO (Id, FileNamePrefix, FileNameExt) VALUES (5, 'calef', 'png');
INSERT INTO TB_DOM_ICONO (Id, FileNamePrefix, FileNameExt) VALUES (6, 'lock', 'png');
INSERT INTO TB_DOM_ICONO (Id, FileNamePrefix, FileNameExt) VALUES (7, 'pir', 'png');
INSERT INTO TB_DOM_ASSIGN (Id, Objeto, Dispositivo, Port, E_S, Tipo, Estado, Flags) VALUES(0, 'Ninguno', 0, 0, 0, 0, 0, 0);
INSERT INTO TB_DOM_GROUP (Id, Grupo) VALUES (0, 'Ninguno');
INSERT INTO TB_DOM_EVENT (Id, Evento, Objeto_Origen, Objeto_Destino, Grupo_Destino, Funcion_Destino, Variable_Destino) VALUES (0,'Ninguno',0,0,0,0,0);
INSERT INTO TB_DOM_FLAG (Id, Variable) VALUES (0, 'Ninguna');
INSERT INTO TB_DOM_FUNCTION (Id, Funcion) VALUES (0, 'Ninguna');
INSERT INTO TB_DOM_USER (id, Usuario, Nombre_Completo, Pin_WEB) VALUES (0, 'nadie', 'Nadie', '****');
INSERT INTO TB_DOM_USER (id, Usuario, Nombre_Completo, Pin_WEB) VALUES (1, 'admin', 'Administrador del sistema', 'admin');
