#!/usr/bin/make -f

all:
	make -C DBUtil
	make -C HWUtil

clean:
	make -C DBUtil clean
	make -C HWUtil clean

install:
	make -C DBUtil install
	make -C HWUtil install

uninstall:
	make -C DBUtil uninstall
	make -C HWUtil uninstall

